name: Singularity Build (docker)
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        singularity_version:
          - '3.7.3'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged
    steps:
    - name: Check out code for the container build
      uses: actions/checkout@v1

    - name: Build Container
      env:
        SINGULARITYENV_GITHUB_SHA: "${{ github.sha }}"
        SINGULARITY_RECIPE: 'Singularity'
        OUTPUT_CONTAINER: 'container.sif'
        IMAGE_URI: 'library://lkirk/default/nb-env:latest'
        SYLABS_TOKEN: "${{ secrets.SYLABS_TOKEN }}"
      run: .github/scripts/build-and-push
