name: Singularity Build (docker)
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        singularity_version:
          - '3.7.1'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged
    steps:
    - name: Check out code for the container build
      uses: actions/checkout@v1

    - name: Build Container
      shell: bash
      env:
        SINGULARITY_RECIPE: Singularity
        OUTPUT_CONTAINER: container.sif
        SYLABS_TOKEN: ${{ secrets.SYLABS_TOKEN }}
        SINGULARITY_LIBRARY: 'library://lkirk/default/nb-env'
      run: |
       set -eu
       if [ -z "${SYLABS_TOKEN}"; then
           echo "NOOOO"
       fi

       if [ -f "${SINGULARITY_RECIPE}" ]; then
           singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
           singularity remote login -p ${SYLABS_TOKEN}
           singularity push ${OUTPUT_CONTAINER} ${SINGULARITY_LIBRARY}
       else
           echo "${SINGULARITY_RECIPE} is not found."
           echo "Present working directory: $PWD"
           ls
       fi
